name: Prepare Release

on:
  push:
    branches:
      - staging

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-release
        run: cargo install cargo-release --locked

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Run cargo-release
        run: cargo release patch --no-confirm --verbose -p prompts-cli --execute
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
