name: Release

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  publish-cli:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Check if version already published
      id: check_version
      run: |
        CRATE_NAME=$(grep -m 1 name prompts-cli/Cargo.toml | sed -E 's/name = "([^"]+)"/\1/')
        CRATE_VERSION=$(grep -m 1 version prompts-cli/Cargo.toml | sed -E 's/version = "([^"]+)"/\1/')
        if cargo search --limit 1 $CRATE_NAME | grep "^${CRATE_NAME} = \"${CRATE_VERSION}\""; then
          echo "Crate version ${CRATE_VERSION} already published. Skipping publish."
          echo "skip_publish=true" >> $GITHUB_OUTPUT
        else
          echo "skip_publish=false" >> $GITHUB_OUTPUT
        fi

    - name: Publish to crates.io
      if: steps.check_version.outputs.skip_publish == 'false'
      run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }} -p prompts-cli
