name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    # This is to prevent the workflow from running on commits made by the release bot
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
    - uses: actions/checkout@v4
      with:
        # We need to fetch all history and tags for cargo-release
        fetch-depth: 0
        # GITHUB_TOKEN has write access to the repo, which is needed to push the new tag.
        # The repository settings must allow GitHub Actions to create and approve pull requests.
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Install cargo-release
      run: cargo install cargo-release --locked

    - name: Configure git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Run cargo-release
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: cargo release patch --execute --no-confirm -p prompts-cli
