name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Print version before release
      run: grep version prompts-cli/Cargo.toml

    - name: Install cargo-release
      run: cargo install cargo-release --locked

    - name: Configure git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Run cargo-release
      run: cargo release patch --no-confirm --verbose -p prompts-cli --no-push --no-publish --execute

    - name: Create Pull Request
      run: |
        TAG_NAME=$(git describe --tags --abbrev=0)
        git checkout -b "release/$TAG_NAME"
        git push origin "release/$TAG_NAME"
        git push origin "$TAG_NAME"
        gh pr create --base main --head "release/$TAG_NAME" --title "Release $TAG_NAME" --body "Release $TAG_NAME"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
