name: Staging CI

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed
    branches:
      - staging

jobs:
  update-lockfile:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # We need to check out the specific commit that triggered the workflow run
          ref: ${{ github.event.workflow_run.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Update Cargo.lock
        run: cargo update

      - name: Commit Cargo.lock changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # Check if there are changes to Cargo.lock and commit them
          if ! git diff --quiet Cargo.lock; then
            git add Cargo.lock
            git commit -m "chore: Update Cargo.lock [skip ci]"
            git push
          fi
